### PR TITLE
allow inheriting from vanilla custom elements

### LINKED ISSUE #4: extending the prototype of an existing custom element should copy over the listeners
When extending an existing custom element that wasn't created with `custom-element`, it'd be rad if the existing listeners would be copied over to the `.on` structure rather than being straight up overwritten. That way it's possible to infinitely extend custom components, even if they're not initially set up with `custom-element`. 

The use case I'm picturing for this is having generic components that are self-contained and are just concerned with updating the component itself, and once you use them in an application you can attach glue code listeners that can listen to changes in other parts of your application. Think that would be a neat separation of concerns, hah.

I'm basing this assumption off reading the code, not verified yet so apologies if I'm opening a redundant issue, hah.

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Closes #4. Uses es6 symbols (through a polyfill) to identify functions generated by `.on` and not confuse them with vanilla custom element listeners. Thanks!
## Changes
- **custom-element**: allow inheriting from custom elements created with native DOM methods in addition to elements created with `custom-element`.

### CODE REVIEW

**Comment by hughsk** [comment]
Awesome, thanks for this man! Let's give it a day or two to give @timoxley a chance to weigh in but otherwise looks good to me :)

**Comment by timoxley** [comment]
LGTM

**Comment by yoshuawuyts** [comment]
And it's merged! Thanks for adding me as a collaborator. I'm not able to release this on npm right now, but if someone could release it as `2.1.0` it'd be grand. :D

**Comment by timoxley** [comment]
@yoshuawuyts done. You're able to publish now too.

**Pull request merged**
